### ISSUE TITLE
Legal Stuff

### ISSUE THREAD

**Issue by ShiroSpectre** [CodeIsJustLikeMagic/SummonerTrackerClientP#3]
Hey,

first of all, thanks for the great work. This tracker is way better than every other I have seen yet.

I want to ask, if you have registered your app on riots developer portal. You stated in the legal stuff, your application is legal, because the other examples are. I dont know about "Summoner", because the link is dead, but the others are clearly using the Riot Web API and not the Live Client API, especially the mobile ones. There are apps like lola, who state that they only got riots confirmation, if they do not calculate haste into the spell cooldowns. Well, nobody can prove if thats true. But the point is, the Live Client API docs state that you have to register the app, even if you only use the Live Client API.
Ultimately, this would give my team and me more confidencce in using your app, without breaking riots policies.

**Comment by CodeIsJustLikeMagic** [comment]
Hi
I haven't registered it yet because from a functional standpoint it wasn't nessesary and it seems like a hassle. I didn't know about the haste calculation restriction, thanks for bringing it up. 
But you are right I should get it registered especially since more people seem to be using it now.

**Comment by fonsua** [comment]
is it bannable to use this program?

:'c

**Comment by CodeIsJustLikeMagic** [comment]
Hi
I've started the verification process. Apparently it can take two weeks until I hear from them.
You probably won't be banned but until the application is verified we are in a bit of a gray area.

**Comment by CodeIsJustLikeMagic** [comment]
Ok, I have done the verification and the app has been approved.
