### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Keyoonz** [CodeIsJustLikeMagic/SummonerTrackerClientP#4]
Hi, 
How do i install it, I downloaded the latest version but dont know how to setup...
Sincerely,
Keyonz

**Comment by CodeIsJustLikeMagic** [comment]
Hi,
You download the .zip file and unpack it. Then you can start the programm by double klicking the .exe file.
(If the programm doesn't start there might be a bug. I haven't checked on it in a while)
